### ISSUE TITLE
Extension does not work if fieldsets are used

### ISSUE THREAD

**Issue by zechendorf** [benwalch/formprocess#4]
Due to the handling of the TypoScript array the extension only checks for form elements on the first level. If there is a fieldset the extension fails to _walk through_ the elements below the fieldset element.

I will have a look into it myself.

**Comment by cubecoffee** [comment]
It's a problem in the function _getFormData()_ in _TYPO3\CMS\Form\PostProcess\UserPostProcessor_. A single element can hold other elements in any depth. There has to be a check if an element is type of _TYPO3\CMS\Form\Domain\Model\Element\FieldsetElement_. If so you have to split the element there. And again think of fieldsets in fieldsets in fieldsets in ...

**Comment by zechendorf** [comment]
@cubecoffee - is this even still relevant? AFAIK TYPO3 version 8 has a completely different form engine (again).

**Comment by cubecoffee** [comment]
@zechendorf We have still customers with running 6.2 LTS systems. So yes it is. But we will fix it by ourself.

**Comment by zechendorf** [comment]
@cubecoffee - thanks for the feedback though!

**Comment by benwalch** [comment]
thanks for the feedback. this extension is no longer maintained.
